### PR TITLE
ssh-ca

### PR DESCRIPTION
**Pull request by phobologic**
Add the project ssh-ca to the list of ssh projects.

### CODE REVIEW

**Comment by phobologic** [comment]
Looks like this isn't maintained any longer - that's too bad.  Closing this out.

**Comment by n1trux** [comment]
It is already in my repo, please feel free to open future PRs there :)

https://github.com/n1trux/awesome-sysadmin

**Comment by phobologic** [comment]
Thanks @n1trux - I don't see ssh-ca in your repo though?  A search for ssh-ca on your repo doesn't show it at least :)

**Comment by n1trux** [comment]
Oh, I'm sorry.
I just looked at your last commit and thought it was about SSH Power Tool...

I just merged this pull request :)
Thank you for contributing!

**Comment by phobologic** [comment]
Awesome - thanks @n1trux .  I'll submit a pull request with a new ssh tool right now!

**Pull request closed without merging**
