### PR TITLE
stormssh

### PR DESCRIPTION
**Pull request by mmontone**
stormssh SSH management tool

### CODE REVIEW

**Comment by n1trux** [comment]
@mmontone since I don't know how to merge commits from non-existing repositories, I manually added stormssh [to a branch of my repo](https://github.com/n1trux/awesome-sysadmin) and credited you in the commit message.

This will soon™ (after merging other pending requests for kahun/awesome-sysadmin) be merged into my repo's (n1trux/awesome-sysadmin) master branch and I would very like you to consider creating pull requests for my repo in the future, too.

Thanks for (involuntarily ;) contributing!

**Comment by mmontone** [comment]
Good! I removed my repository because the merge was taking too much time and I thought you were not going to do it

**Comment by kahun** [comment]
Already reported, thanks

**Comment by emre** [comment]
:dancers:

**Pull request closed without merging**
