### PR TITLE
add NetData to Metric tools

### PR DESCRIPTION
**Pull request by bitintheskud**
NetData is a real-time performance monitoring. Must have ! 

Name : NetData

Project Page : http://my-netdata.io/
Github page : https://github.com/firehol/netdata/

Category: Metric & Metric Collection

### CODE REVIEW

**Comment by Oxicode** [comment]
:+1:

**Comment by issmirnov** [comment]
Dupe of #398. Seems it got lost in the pile.

**Comment by dbinoj** [comment]
Seems like lots of PRs got lost in the pile :disappointed:

**Comment by kmonsoor** [comment]
Hello unknown visitor, if you visiting this page **and** want `netdata` to be added in the awesome-list, please vote (by using 👍) on the first related PR, #428

**Comment by kahun** [comment]
Thanks

**Pull request merged**
