### PR TITLE
added "Advanced SSH Config" project

### PR DESCRIPTION
**Pull request by mgarces**
Enhances ssh_config file capabilities.

NOTE: This program is called by ProxyCommand from lib-ssh.

It works transparently with :
ssh, scp, rsync, git and even desktop applications depending on lib-ssh (for instance Tower, Atom.io, SSH Tunnel Manager, etc)

### CODE REVIEW

**Comment by n1trux** [comment]
this is not how a PR works. Please remove your repo-specific (sysadmin.pt-specific?) markdown and only commit new applications.

I added your suggestion to my repo [and credited you](https://github.com/n1trux/awesome-sysadmin/commit/d9d7075ee85e3067606bce38fab0438e60a3d7ba) ;)

**Comment by mgarces** [comment]
oh sorry about the sysadmin.pt stuff... I am using this project to generate a page inside my site, and I ended up mixing git repos, sorry about that!

**Comment by mgarces** [comment]
@n1trux what is the oficial repo for Awesome Sysadmin? your or kahun? It seems @kahun  is a bit outdated... Also, sorry about this mess, still trying to figure out how have I done this, and how can I fix it... :)

**Comment by n1trux** [comment]
@mgarces there is no "official" repo. kahun/awesome-sysadmin is the "original" one and there are a lot of forks. Sadly @kahun seems to be a bit busy at the moment, so I merged a few PRs into my repo (n1trux/awesome-sysadmin).

If you like you can create PRs for my repo, maybe it'll get merged into kahun's eventually.

You can create a branch in your repo for creating pull requests (let it track kahun/master or another repo you like, e.g. mine) and use the master branch for your project. This way you could merge commits from the upstream and still have your own flavor.

For merging only certain commits, you maybe have to read about cherry-picking and commits, but I'd rather go with the branch option. If you need assistance, there is e.g. a #git channel on freenode IRC.

**Comment by mgarces** [comment]
Thank you so much for the help. After the mess I made, I read a bit more, and talked to more experienced git users, and they all said to me to use the branch option for the PR, keeping my stuff in the master, just like you said! Thanks a lot, I will fork your repo, since I feel it's getting more attention for now.

**Pull request closed without merging**
