### PR TITLE
Add xiringuito - SSH-based "VPN for poors"

### PR DESCRIPTION
**Pull request by ivanilves**
Add xiringuito - SSH-based "VPN for poors"

### why it is awesome
`xiringuito` is awesome, because:
* easy to install (no dependencies, no configurations)
* allows you to manage one, few or many connections easily (and connect em simultaneously if you want)
* it has `xaval` connection manager - a tool that may record and later re-use your connection profiles
* though you are free to use or not to use `xaval` connection manager - people also use `xiringuito` for ad-hoc onetime connections
* Just look at this GIF :wink:

### CODE REVIEW

**Comment by ivanilves** [comment]
Hey, any reason why we can not merge this? :wink:  

ping @kahun :innocent: 

Thanks!

**Comment by ivanilves** [comment]
Closed due inactivity :ghost:

**Comment by pryorda** [comment]
Maybe sshuttle should replace this?

**Comment by ivanilves** [comment]
> Maybe sshuttle should replace this?

Great question @pryorda !

In short: **Not really!** :wink:  

More complete: https://github.com/ivanilves/xiringuito#whats-the-difference-between-xiringuito-and-sshuttle

**Comment by pryorda** [comment]
:+1:

**Comment by ivanilves** [comment]
closing due to lack of activity :slightly_smiling_face:

**Pull request closed without merging**
