### PR TITLE
Added QEMU to Virtualization section

### PR DESCRIPTION
**Pull request by mrvaldes**

### CODE REVIEW

**Comment by tas50** [comment]
+1

**Comment by carloscarcamo** [comment]
+1

**Comment by shel3over** [comment]
should be on the TOP !

**Comment by n1trux** [comment]
@mrvaldes since you deleted your repo, I couldn't automatically merge your pull request [into a branch of my repo](https://github.com/n1trux/awesome-sysadmin).

I however added it myself and credited you in the commit message!

This will soon™ (after merging other pending requests for kahun/awesome-sysadmin) be merged into my repo's (n1trux/awesome-sysadmin) master branch and I would very like you to consider creating pull requests for my repo in the future, too.

Thanks for (involuntarily ;) contributing!

**Comment by mrvaldes** [comment]
@n1trux Sorry about the deleted repo. Great to see a better maintained branch. I'll definitely check your repo and contribute what I can

**Comment by kahun** [comment]
Already reported, thanks

**Pull request closed without merging**
